server:
  port: 8080
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的
      # 而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher

mybatis-plus:
  type-aliases-package: com.myAwesomeWeb.*.domain,com.myAwesomeWeb.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
  reasonable: true
camunda:
  bpm:
    admin-user:
      id: demo
      first-name: admin
      password: admin
    database:
      type: mysql
      schema-update: true
    filter:
      create: All tasks
    # 禁止自动部署resources下面的bpmn文件
    auto-deployment-enabled: false

