server:
  port: 8080
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的
      # 而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher

mybatis-plus:
  type-aliases-package: com.myAwesomeWeb.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
